name: qazaq_republic_classic
description: Классикалық киім үлгілерін сататын Qazaq Republic Classic онлайн дүкені.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  sqflite_common_ffi_web: ^0.4.0
  sqflite_common: ^2.5.0
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  http: ^1.1.0
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.11
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  image_picker_web: ^3.1.1
  crypto: ^3.0.3
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/assets/images/
    - assets/assets/icons/
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #         weight: 500